EMAIL_USER = "harshuaz11@gmail.com"
EMAIL_PASS = "qzmg lttk qlql koex"
ALERT_RECIPIENT = "harshuaz11@gmail.com"
AIRNOW_API_KEY = "713D415F-1E68-48CA-B15B-9153C71A182C"
GEM_KEY = AIzaSyBN9OR6RodwAAd7KPl8HPlDG448mKpsCsg
